#!/usr/bin/env python3
"""
masumi-agent - Main Entry Point
Generated by masumi init

This is the entry point for your Masumi agent.
Run this file to start the agent server.
"""

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

from masumi import run
from agent import process_job

# Define input schema
INPUT_SCHEMA = {
    "input_data": [
        {
            "id": "prospect_name",
            "type": "string",
            "name": "Prospect Name"
        },
        {
            "id": "prospect_email",
            "type": "string",
            "name": "Prospect Email"
        },
        {
            "id": "prospect_role",
            "type": "string",
            "name": "Prospect Role"
        },
        {
            "id": "company_name",
            "type": "string",
            "name": "Company Name"
        },
        {
            "id": "company_industry",
            "type": "string",
            "name": "Company Industry"
        },
        {
            "id": "company_size",
            "type": "options",
            "name": "Company Size",
            "options": ["startup", "small", "medium", "large", "enterprise"]
        },
        {
            "id": "intent_signal",
            "type": "options",
            "name": "Intent Signal Type",
            "options": [
                "job_change",
                "funding_event",
                "technology_adoption",
                "company_growth",
                "industry_trend"
            ]
        },
        {
            "id": "intent_description",
            "type": "string",
            "name": "Intent Description"
        }
    ]
}

# Main entry point
if __name__ == "__main__":
    run(
        start_job_handler=process_job,
        input_schema_handler=INPUT_SCHEMA
    )